fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem

grpc:
  enabled: true

connectors:
  zeromq_connector:
    protocol: zeromq
    settings:
      common:
        endpoint: tcp://zeromq-pub:5555
        pattern: pubsub
      clients:
        sub:
          topics: [zeromq-topic]

