quic:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
grpc:
  enabled: true
connectors:
  connector:
    type: zmq4
    settings:
      common:
        # Fujin binds PUB here; external ZMQ SUB clients connect
        publish_bind: "tcp://*:5555"
        # Fujin binds SUB here; external ZMQ PUB clients connect
        subscribe_bind: "tcp://*:5556"
      clients:
        events:
          produce_topic: "events"
          consume_topics: ["events"]
        alerts:
          produce_topic: "alerts"
          consume_topics: ["alerts", "events"]
