[package]
name = "fujin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Composable high-performance message broker gateway"
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[features]
default = []
grpc = ["fujin-runtime/grpc"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fujin-configurator.workspace = true
fujin-connector.workspace = true
fujin-error.workspace = true
fujin-runtime.workspace = true
fujin-middleware.workspace = true
fujin-native.workspace = true
fujin-transport.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
yaml_serde.workspace = true
fujin-transport-tcp.workspace = true
fujin-connector-nats.workspace = true
