fujin:
  transports:
    - type: tcp
connectors:
  connector:
    type: kafka_franz
    settings:
      common:
        brokers: [localhost:9092, localhost:9093, localhost:9094]
        tls:
          enabled: false
          server_cert_pem_path: ./examples/assets/certs/fujin.io.pem
          server_key_pem_path: ./examples/assets/certs/fujin.io-key.pem
      clients:
        pub:
          produce_topic: my_pub_topic
        sub:
          consume_topics: [my_pub_topic]
          group: fujin2
