services:
  fujin:
    image: fujin:redis_rueidis_pubsub-${BUILD_TAG}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FUJIN_CONNECTORS: github.com/fujin-io/fujin/public/plugins/connector/redis/rueidis/pubsub
        FUJIN_GO_TAGS: quic,tcp,grpc
    container_name: fujin
    environment:
      FUJIN_CONFIGURATOR: yaml
      FUJIN_CONFIGURATOR_YAML_PATHS: /assets/config/config-redis_rueidis_pubsub.yaml
    ports:
      - "4848:4848/udp"
      - "4849:4849"
    volumes:
      - ./assets:/assets
    restart: always