FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /zeromq-socket ./cmd/zeromq-socket

FROM alpine:3.19

WORKDIR /

COPY --from=builder /zeromq-socket /zeromq-socket

EXPOSE 5555

ENTRYPOINT ["/zeromq-socket"]

