services:
  fujin:
    image: fujin:zmq4-${BUILD_TAG}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FUJIN_CONNECTORS: github.com/fujin-io/fujin/public/plugins/connector/zeromq/zmq4
        FUJIN_GO_TAGS: quic,tcp,grpc
    container_name: fujin
    environment:
      FUJIN_CONFIGURATOR: yaml
      FUJIN_CONFIGURATOR_YAML_PATHS: /assets/config/config-zmq4.yaml
    ports:
      - "4848:4848/udp"
      - "4849:4849"
      - "5555:5555"  # ZMQ PUB (Fujin binds, external SUBs connect)
      - "5556:5556"  # ZMQ SUB (Fujin binds, external PUBs connect)
    volumes:
      - ./assets:/assets
    restart: always
