services:
  fujin:
    image: fujin:zeromq-${BUILD_TAG}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        FUJIN_CONFIGURATORS: github.com/fujin-io/fujin/public/plugins/configurator/all
        FUJIN_CONNECTORS: github.com/fujin-io/fujin/public/plugins/connector/zeromq
        FUJIN_GO_TAGS: fujin,grpc
    container_name: fujin-zeromq
    environment:
      FUJIN_CONFIGURATOR: file
      FUJIN_CONFIGURATOR_FILE_PATHS: /assets/config/config-zeromq.yaml
    ports:
      - "4848:4848/udp"
      - "4849:4849"
    volumes:
      - ./assets:/assets
    restart: always

