{{- if eq .Values.mode "standalone" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fujin.fullname" . }}
  labels:
    {{- include "fujin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fujin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "fujin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fujin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FUJIN_CONFIGURATOR
              value: "yaml"
            - name: FUJIN_CONFIGURATOR_YAML_PATHS
              value: "/config/config.yaml"
            - name: FUJIN_LOG_LEVEL
              value: {{ .Values.log.level | quote }}
            - name: FUJIN_LOG_TYPE
              value: {{ .Values.log.type | quote }}
          ports:
            - name: tcp
              containerPort: {{ .Values.ports.tcp }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.ports.grpc }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.ports.health }}
              protocol: TCP
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "fujin.fullname" . }}
{{- end }}
